### ISSUE TITLE
Settings: Compiler choice and header paths

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/Paladin#23]
Commenting for clarification.
When creating a makefile with Paladin 
SYSTEM_INCLUDE_PATHS = /boot/system/develop/headers/cpp
However, this is a BeOS path. Depending on whether gcc2 or gcc5 is being used, the Haiku path is:
gcc2 - /boot/system/develop/headers/c++/2.95.3
gcc5 - /boot/system/develop/tools/x86/lib/gcc/i586-pc-haiku/5.4.0/include/c++

**Comment by Vidrep** [comment]
X86_64 - /boot/system/develop/tools/lib/gcc/x86_64-unknown-haiku/5.4.0/include/c++

**Comment by vchrombie** [comment]
We don't what the user is using right.
Then how can we solve this?

**Comment by Vidrep** [comment]
Maybe a user setting where the appropriate gcc compiler and ARCH is selected from a list?

**Comment by KevinAdams05** [comment]
A setting for this would work fine for me

**Comment by adamfowleruk** [comment]
Title was: Cpp header files path different on Haiku

**Comment by adamfowleruk** [comment]
I've abstracted out the local path for headers and libs as it didn't make sense to hard code these in to the project files. These are now check on both load and save, effectively upgrading any hardcoded project paths. On load, the placeholder string is replaced by the local headers path.

This does have the effect of make the project files for this version of Paladin incompatible with previous versions. May have to consider setting this version to 2.0 instead of 1.5 as it's a fundamental change.
