### ISSUE TITLE
Update revision, version info

### ISSUE THREAD

**Issue by scottmc** [HaikuArchives/Paladin#42]
As major and minor issues are resolved in Paladin, we should consider when/if to do major and minor point releases.  The appropriate files will need to get updated to reflect this versioning info and then a matching tagged release can be made. We should verify Paladin's stability at each release prior to tagging.

**Comment by adamfowleruk** [comment]
I quite like using GitHub's Milestone functionality to group issues together. I decide when a Milestone is near completion what the version number should be (E.g. v1.2 or v2.0). Some Milestones become tidying up releases, others major new bits of functionality. As new bugs/enhancements come in, they're grouped in to milestones. Developers are encouraged to work on the next milestone rather than picking and choosing.

My workflow:-

1. Each new development is logged as an issue.
1. A feature branch is created for that issue - feature-ISSUENUM
1. Once each feature is complete the branch feature-ISSUENUM is merged in to develop via a PR
1. Once all features in a milestone are merged in to develop, pre-release testing is done (some people use a seaparate release branch at this point as a bridge between develop and master)
1. Once tested, develop is merged in to master, and tagged as a release v1.0 etc

Not sure if this is what you want for this project, but it's the way I've seen other projects work before. (Admittedly, mostly Java projects rather than CPP).

Best way in a code to track version is to have a Version.h file from what I've seen. I've never seen a satisfactory automated way to link git release tags and Makefile/header file version defines.

**Comment by pulkomandy** [comment]
It seems you are mostly in charge of this project now. Tell us if you need something changed in github project settings you can't access.

**Comment by adamfowleruk** [comment]
I wouldn't go that far! I'm just a Johnny come lately really.

I'd be happy to help out any way I can though. Main thing I can think of is the ability to create branches on HaikuArchives/Paladin, create/edit milestones, and so on. I'm not sure what perms on GitHub that would require...

**Comment by scottmc** [comment]
If you have any questions about Paladin and the code in general, the original author darkwyrm is still around to ask questions of, he just doesn't write much code anymore.  His email address is in the README.  If you end up working on more than just Paladin on HaikuArchives we can add you to the team.  Nice work so far.

**Comment by adamfowleruk** [comment]
Thanks. I'm just poking around the code at the moment seeing what works, what doesn't work. I'll probably take a look at Pe just to get familiar with the code base. Happy to help out however I can.

**Comment by adamfowleruk** [comment]
OK I think I'd like the following to be added to this GitHub project, if it's ok with everyone? 

Mostly its about having Milestones as I tend to create tonnes of small issues and group them rather than big issues that take a long time to iterate through.

- Add a 'develop' branch off of master - Enables GitFlow workflow for git that doesn't break the 'master'
- Milestones (Full release after each milestone)
  - "1 Stock take and bug fixing" - for any current bugs, out of date code that needs fixing/replacing, for the app to work as currently designed. App version management. Release build process agreed.
  - "2 Paladin on Paladin" - eat own dog food. Get the app to a place where it can successfully edit the Paladin source code, Locale files, do a full build (i.e. execute buildscript), checkin/out feature branches
  - "3 Developer workflow" - Integrate to other existing tools that may already exist. E.g. GitHub Issues app, WebPositive to view GitHub project/issues, catkeys, Jamfile builds, editors for all file types commonly in projects. Make it easy to code/build/test/fix in C++. Make managing large projects easier. Perhaps also some more app templates relevant to Haiku (E.g. "Paladin Tools Extension", "Haiku Screensaver", and so on), Jump to function declaration/implementation/API documentation. 
   - "4 UI Experiments" - A series of feature branches with big changes to test out the more radical ideas that may fundamentally change how the app works. E.g. 1. test out an embedded code editor instead of Pe. 2. Folder navigation versus group navigation views for projects
  - "5 Maintenance release" - Fix the numerous issues the previous features are bound to have created. Also for rejigging documentation.
  - "6 Testing" - Write a tonne of tests for internals of Paladin, including especially Project file management, Source code file management, and Paladin Tools plugin mechanism. May require some refactoring to move logic out of UI classes. Also features to make and run tests for a project within Paladin itself. (Another Paladin in Paladin eating own dog food feature)
  - No date on any of the above Milestones please
- Ability to merge feature branches in to develop (I don't need to do it to master if we have a develop branch) - due to the number of feature branches, I may give @scottmc RSI if I keep issuing this may PRs!

**Comment by scottmc** [comment]
Sounds like a plan.  Feel free to create the milestones and assign issues to the matching milestones.

**Comment by adamfowleruk** [comment]
I don't have enough permissions to create Milestones I'm afraid. Would also ideally like to create and assign labels too. I think both those things are either 'Write' permissions or 'Admin' permissions...

**Comment by adamfowleruk** [comment]
Ah turns out I don't have permissions to add labels to issues, re-order issues, re-order milestones, or add issues to milestones, or create labels. Not sure what to suggest...

**Comment by scottmc** [comment]
try now, i think i did it right, you should have permissions on Paladin now.

**Comment by adamfowleruk** [comment]
Looks good, thanks!
